name: elm327_scanner
description: Aplicación Flutter para escanear vehículos usando un adaptador ELM327 v1.5.
version: 1.0.0+1
publish_to: "none"
environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
